package vu.lt.mybatis.model;

public class StudentProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_PROJECT.STUDENTS_ID
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    private Integer studentsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_PROJECT.PROJECTS_ID
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    private Integer projectsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_PROJECT.STUDENTS_ID
     *
     * @return the value of PUBLIC.STUDENT_PROJECT.STUDENTS_ID
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    public Integer getStudentsId() {
        return studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_PROJECT.STUDENTS_ID
     *
     * @param studentsId the value for PUBLIC.STUDENT_PROJECT.STUDENTS_ID
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    public void setStudentsId(Integer studentsId) {
        this.studentsId = studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_PROJECT.PROJECTS_ID
     *
     * @return the value of PUBLIC.STUDENT_PROJECT.PROJECTS_ID
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    public Integer getProjectsId() {
        return projectsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_PROJECT.PROJECTS_ID
     *
     * @param projectsId the value for PUBLIC.STUDENT_PROJECT.PROJECTS_ID
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    public void setProjectsId(Integer projectsId) {
        this.projectsId = projectsId;
    }
}