package vu.lt.mybatis.dao;

import java.util.List;
import vu.lt.mybatis.model.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sat Mar 23 23:07:25 EET 2019
     */
    int updateByPrimaryKey(Project record);
}