package vu.lt.mybatis.dao;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Student;
import java.util.List;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Thu Mar 21 12:05:49 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbgethod corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Thu Mar 21 12:05:49 EET 2019
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This m
     Student selectByPrimaryKey(Integer id);

     /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Thu Mar 21 12:05:49 EET 2019
     */
    List<Student> selectAll();

    /**
     *
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Thu Mar 21 12:05:49 EET 2019
     */
    int updateByPrimaryKey(Student record);
}