package vu.lt.mybatis.dao;
import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Team;
import java.util.List;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Thu Mar 21 12:03:23 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Thu Mar 21 12:03:23 EET 2019
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Thu Mar 21 12:03:23 EET 2019
     */
    Team selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Thu Mar 21 12:03:23 EET 2019
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Thu Mar 21 12:03:23 EET 2019
     */
    int updateByPrimaryKey(Team record);
}